### ISSUE TITLE
[Streamlink error message] No connection adapters were found

### ISSUE THREAD

**Issue by heywolf15** [avotoko/avgle-HLS-playlist-downloader#1]
Unable to open URL  No connection adapters were found

**Comment by avotoko** [comment]
It seems that you have specified the wrong location of the downloaded m3u8 file to Streamlink.
Streamlink accept only url not local file path. You need to convert local path to url.

[Windows]
local path: c:\temp\avgle.m3u8
url: file:///c:/temp/avgle.m3u8
command line:
`streamlink --http-header referer=https://avgle.com/ file:///c:/temp/avgle.m3u8 best`

[Unix]
local path: /etc/avgle.m3u8
url: file:///etc/avgle.m3u8
command line:
`streamlink --http-header referer=https://avgle.com/ file:///etc/avgle.m3u8 best`

**Comment by heywolf15** [comment]
Thanks but I got another problem
Unable to open url, 404 client error: none for url:...

**Comment by avotoko** [comment]
The url described in the playlist(m3u8 file) retrieved by AvgleHPD becomes invalid after a while.
Try to run Streamlink as soon as possible after retrieving the playlist.

P.S.
If you write the error message without omitting it, it will be easier to give proper advice.
In this case, whether the url in the error message is file:// or https:// is very important information.

**Comment by heywolf15** [comment]
It's working now, don't know what happen yesterday even with the newest retrieved file and correct url.
Thank you for the advice and updating the README for everyone.

Are you know that the download can be done with YouTube-dl?
I heard it can download m3u8 and convert it to another format
I'm very curious, since I'm just using the (GUI) Tartube
Thanks again

**Comment by avotoko** [comment]
I don't know how to download using youtube-dl.
Sorry I couldn't help.

**Comment by heywolf15** [comment]
No problem, thanks
