### ISSUE TITLE
javmost

### ISSUE THREAD

**Issue by didvc** [avotoko/avgle-HLS-playlist-downloader#4]
Hey. Firstly let me say thank you for the great work. 

I'd like to know if you have a plan to deal with javmost.com? Thanks.

**Comment by avotoko** [comment]
At the moment I have no interest in writing and publishing download scripts for sites other than Avgle.
A quick look suggests that javmost can be downloaded using existing downloaders or the mp4 / m3u8 URLs that appear in the network tab of the developer tools.
If you don't know the actual download procedure, it's a good idea to ask in the appropriate forum. The Video Streaming Downloading forum in VideoHelp Forum is very helpful.

**Comment by didvc** [comment]
oh you are right. I tried the Video downloadhelper extension with the site on a changed browser it worked. Thanks for the advice.
