### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by raijin-tyu** [avotoko/avgle-HLS-playlist-downloader#6]
its working some week ago, but today got an error `error: Unable to open URL: http://./avgle.m3u8 (encoding with 'idna' codec failed (UnicodeError: label empty or too long))`

**Comment by avotoko** [comment]
At first glance, it seems that you have specified the wrong location for the m3u8 file on the streamlink command line.
The location of the m3u8 file must start with `file:`, not `http:` as in `http://./avgle.m3u8`. Please follow the instructions in the documentation.
Also, if your OS is Windows, it is easy to use avgleHPD-dl.bat from my blog. The URL for the blog is in the documentation.

**Comment by raijin-tyu** [comment]
oops, yes you are right, its because I write just `./avgle.m3u8` instead of `file://./avgle.m3u8`, its working now :+1: , no I'm using ubuntu, thanks buddy.
